---
site_name: "im-cim-v100"
theme:
  name: material
  # palette:
  #  scheme: slate
  #  primary: cyan
  features:
    - content.tabs.link
plugins:
  - search
  - mermaid2
nav:
  # - Home: home.md
  - Index: index.md
  - About: about.md
site_url: https://ritger-alliander.github.io/im-cim-v100
repo_url: https://github.com/ritger-alliander/im-cim-v100

# Uncomment this block to enable use of Google Analytics.
# Replace the property value with your own ID.
# extra:
#   analytics:
#     provider: google
#     property: G-XXXXXXXXXX
